### ISSUE TITLE
Python controller cannot connect ...

### ISSUE THREAD

**Issue by khoatranrb** [isl-org/OpenBot#351]
![image](https://user-images.githubusercontent.com/48320778/233153439-36ee33b6-291a-46ab-b0c4-711f852e4aa6.png)

What should I do now?

**Comment by thias15** [comment]
Are phone and computer in the same network? Is connection mode set to RTSP? Did you toggle the controller mode to the phone icon?

**Comment by khoatranrb** [comment]
I followed the guide in Python controller: connect to same network, turn to phone icon. I am not a wireless expert so can you give me a guide on RTSP connection mode?

**Comment by khoatranrb** [comment]
![image](https://user-images.githubusercontent.com/48320778/234057028-a5e5330d-1b2a-48cf-97b4-95cc68f8bd9e.png)

However, it has been stuck at line 322. So I think RTSP is not problem.

**Comment by sanjeevitinker** [comment]
Hello @khoatranrb ,

I encountered the same issue with the connection, and I believe I found the solution. The problem seems to be related to a mismatch in the port numbers set in the OpenBot Robot App and the Python application.

In the Python code (keyboard-click.py, keyboard-pygame.py, common.py), the default port is set to 19400:

`python - self.sock.bind(("0.0.0.0", 19400))`

However, in the OpenBot Robot App, the default port is configured as 8081. To establish a successful connection, these port numbers should match.

To resolve the issue, you can update the Python code to use port 8081:

`self.sock.bind(("0.0.0.0", 8081))`

After making this change, the Python application should connect to the OpenBot Robot App without any issues.

I hope this helps!
